### ISSUE TITLE
Publish erlang-oauth on hex.pm?

### ISSUE THREAD

**Issue by kpanic** [tim/erlang-oauth#29]
Hi,

Would it be possible to publish your package on https://hex.pm?

That's it, thanks in advance :)

**Comment by tim** [comment]
Possible obviously, what's your use case exactly? Hex is an Elixir package manager--for Elixir projects it would make more sense to be using an Elixir library like [oauther](https://github.com/lexmag/oauther).

**Comment by kpanic** [comment]
Hi @tim first of all, thanks for your answer!

hex.pm is a generic package manager for erlang projects, you can find https://hex.pm/packages/cowboy for example.

My use case would be to publish a package of mine that depends on https://github.com/parroty/extwitter which depends on `erlang-oauth`. Since `erlang-oauth` is not published in hex.pm, to integrate extwitter in a library means:

* Add a dependency of extwitter
* Point to `erlang-oauth` github

Instead of only including the extwitter dep which would download also `erlang-oauth` (if on hex.pm)

Thanks a lot @tim I hope to have clarified the issue! :)

**Comment by tim** [comment]
@kpanic I understand that use case but I don't think having to specify 2 dependencies instead of 1 is a *huge* inconvenience, considering thay there are 2 different languages involved. I agree it would be easier if you only had to specify extwitter as a dependency, but I think the best way to achieve that is for extwitter to use an Elixir library instead of erlang-oauth.

I don't want the hassle/cost of supporting everybody's favourite build tool or package manager and the resulting [file sprawl](https://github.com/testdouble/testdouble.js/pull/179#issuecomment-273213412). Makefile, Emakefile, and .travis.yml is enough. If you want to use rebar in your project, you can. If you want to write code in Elixir, you can.

This [has come up before](https://github.com/tim/erlang-oauth/issues/25), I'll open an issue on extwitter to get things started and someone more suitably motivated can pick that up :)
